### ISSUE TITLE
Allow using `config.js`

### ISSUE THREAD

**Issue by viceice** [renovatebot/helm-charts#119]
Allows to require additional files and merge configs on runtime.

**Comment by cbrancoeuipo** [comment]
Hello everyone!

First and foremost I am very new in using github tickets, thus the structure of this message might not be the best.

Before asking my question this is my current stack:

-Kubernetes
-Helm
-Bitbucket-server
-Private artifact repository
-ArgoCD

I am trying to deploy renovate via helm. So far everything went great, managed to get updates for several packages from the official repos (such as node updates).
However, when I try to setup hostRules for resolving the lookups in my private Nexus server nothing changes (having one config.json per project repository). The bot is still opening PR's for updates from the official repositories (both node and others).

Does this issue mean that renovate deployed via helm is not capable of merging the values.yaml config (from the bot deployment) with the config.json in each bitbucket repository (with custom hostRules)? 

Below you can find some of the configuration options I have setup. Forgive me if I am mixing concepts but I am trying to understand as I go, despite frequently visiting the documentation.

PS: The npm repo contains a .nmprc file already defined. I have also noticed that despite changing the debug level (trace, debug,...), I am getting very little information in the ArgoCD logs, and consequently the pod logs (only Info: is being shown, no messages for connection attempts, status,..).

Renovate bot values.yaml:

`renovate:
  # See https://docs.renovatebot.com/self-hosted-configuration
   config: |
     {
       "platform": "bitbucket-server",
       "endpoint": "*****",
       "username": "testusername",
       "password": "testpassword",
       "autodiscover": false,
       "dryRun": false,
       "printConfig": true,
       "requireConfig": true,
       "onboarding": true,
       "gitAuthor": *****",
       "baseBranches": ["integration"],
       "reviewers": ["****"],
       "onboardingConfig": { "extends": ["config:base"] },
       "logLevel": "debug",
       "separateMinorPatch": true,
       "repositories": ["abc/renovate", "abc/some-npm-repo", "abc/some-maven-repo"]
     }`


npm repo renovate.json:

`{  
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["config:base"],
  "automergeType": "pr",
  "packageRules": [{
    "managers": ["npm"],
    "registryUrls": ["http://company.artifact.registry"]
  }],
  "hostRules": [
	{
	  "baseUrl": "http://company.artifact.registry",
	  "token": "the_registry_token"
	}
  ]`


Maven repo renovate.json:

`{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "automergeType": "pr",
  "maven": {
    "enabled": true
  },
  "docker": {
    "enabled": false
  },
  "hostRules": [
    {
      "platform": "maven",
      "endpoint": "http://myprivateendpoint/nexus/repository/public/",
      "username": "nexuspubuser",
      "password": "nexuspubpass"
    },
    {
      "platform": "maven",
      "endpoint": http://myprivateendpoint/nexus/repository/releases/",
      "username": "nexusreluser",
      "password": "nexusrelpass"
    },
    {
      "platform": "maven",
      "endpoint": "http://myprivateendpoint/nexus/repository/snapshots/",
      "username": "nexussnapuser",
      "password": "nexussnapuser"
    }
  ],
  "packageRules": [
    {
      "managers": [
        "maven"
      ],
      "registryUrls": [
        "http://myprivateendpoint/nexus/repository/public/",
        "http://myprivateendpoint/nexus/repository/releases/",
        "http://myprivateendpoint/nexus/repository/snapshots/"
      ]
    }
  ]
}`

In the above config, the maven repo, despite having wrong endpoints configured renovate still goes to the default maven repository (https://repo.maven.apache.org/maven2/) even thought the endpoint is not specified. I confirm this by having PR with official version updates, rather than a connection error message.

Expected behaviour: Error message since I am manually defining inexistent endpoints.
Current behaviour: Defaults to official repositories with no warning/error. No status/message/warn in the logs for the defined endpoints.

**Comment by viceice** [comment]
Fixed by #116 and #120
