### ISSUE TITLE
ArgoCD:  "You must have atleast batch/v1beta1 to use CronJob"

### ISSUE THREAD

**Issue by viceice** [renovatebot/helm-charts#145]
Unfortunately, this PR broke deployment with ArgoCD, as it only tells Helm that `batch/v1` is available (by specifying `--api-versions batch/v1` as an argument to `helm template`). This results in the "You must have atleast batch/v1beta1 to use CronJob" error.

I don't know if this should be fixed here, but this chart is the only one I know that has this problem. Would it be fine to only check for `batch/v1beta1` or `batch/v1` respectively instead of `batch/v1/CronJob`?

_Originally posted by @timoschwarzer in https://github.com/renovatebot/helm-charts/issues/144#issuecomment-888322276_

**Comment by viceice** [comment]
It's a ArgoCD issue. see argoproj/argo-cd#3594

**Comment by viceice** [comment]
As a workaround we can add an optional api versions override to the values file. But this needs another community pr.

**Comment by timoschwarzer** [comment]
@viceice thanks so much for the workaround! ❤️

**Comment by timoschwarzer** [comment]
> It's a ArgoCD issue. see [argoproj/argo-cd#3594](https://github.com/argoproj/argo-cd/issues/3594)

I finally found time to read through this. Unfortunately, this issue is a different one since I was not using the CLI and `--api-versions` flags were passed down to helm by ArgoCD.

This is the error message from ArgoCD:

`rpc error: code = Unknown desc = "helm template . --name-template renovate --namespace renovate --values values.yaml --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions apps/v1 --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1beta1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions policy/v1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1 --api-versions discovery.k8s.io/v1beta1 --api-versions flowcontrol.apiserver.k8s.io/v1beta1 --api-versions acme.cert-manager.io/v1 --api-versions acme.cert-manager.io/v1beta1 --api-versions acme.cert-manager.io/v1alpha3 --api-versions acme.cert-manager.io/v1alpha2 --api-versions cert-manager.io/v1 --api-versions cert-manager.io/v1beta1 --api-versions cert-manager.io/v1alpha3 --api-versions cert-manager.io/v1alpha2 --api-versions helm.cattle.io/v1 --api-versions k3s.cattle.io/v1 --api-versions monitoring.coreos.com/v1 --api-versions monitoring.coreos.com/v1alpha1 --api-versions upgrade.cattle.io/v1 --api-versions argoproj.io/v1alpha1 --api-versions dns.hetzner.com/v1alpha1 --api-versions security-profiles-operator.x-k8s.io/v1alpha1 --api-versions traefik.containo.us/v1alpha1 --api-versions longhorn.io/v1beta1 --api-versions metrics.k8s.io/v1beta1 --include-crds" failed exit status 1: Error: template: renovate/charts/renovate/templates/cronjob.yaml:6:8: executing "renovate/charts/renovate/templates/cronjob.yaml" at <fail "\n\n ERROR: You must have at least batch/v1beta1 to use CronJob">: error calling fail: ERROR: You must have at least batch/v1beta1 to use CronJob Use --debug flag to render out invalid YAML`

Chart version 25.63.1, ArgoCD version 2.0.5 (latest)

**Comment by viceice** [comment]
`--api-versions batch/v1 --api-versions batch/v1beta1` is not enough, as `CronJob` is available in `batch/v1` since v1.21+, but api version `batch/v1` is available in older kubernetes, so i need to test full api version. with #147 you can manually override the api version for argocd by values.yaml
