### ISSUE TITLE
Exec format error while running

### ISSUE THREAD

**Issue by ajax-pyvovarov-y** [renovatebot/helm-charts#289]
Hello!
Following the official manual, I am running helm chart:
`
helm install --generate-name --set renovate.config='\{\"token\":\"...\"\}' renovate/renovate
`
But each time gets a very unclear error: `exec /usr/local/bin/docker-entrypoint.sh: exec format error` when pod trying to start. 
What I am doing wrong?

**Comment by audibleblink** [comment]
![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

I swear I didn't accidentally switch CPUs on a random node in my cluster. And I get the same error whether I force the amd64 of arm64 image. Host node is ubuntu 22.04. This was working fine prior to v27. But if I downgrade, past version that were working, now don't UNLESS I go all the way back to 35.14.4.

I've never seen that error on a problem that _isn't_ architecture/OS related.

WHAT DID YOU SEE @ajax-pyvovarov-y?

This is probably something on my cluster, and not a renovate issue, which is why I didn't open a new issue, but I hope someone has seen something like this before?

**Comment by viceice** [comment]
@audibleblink please open a new discussion and provide more details so we can help
